<a href="https://colab.research.google.com/github/siddartharc/AI-AmRITA/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Numpy in **lists**

In [2]:
PythonList = [69,18,1,45]
print(PythonList)

[69, 18, 1, 45]


Numpy in **array**

In [3]:
numpy_array = np.array(PythonList)
numpy_array

array([69, 18,  1, 45])

In [5]:
a = numpy_array+15
print(a)

[84 33 16 60]


In [6]:
a = np.array([1,2,13])
print(a)

[ 1  2 13]


In [7]:
b = a +15
print(b)

[16 17 28]


In [8]:
print(a.shape)
print(a.dtype)

(3,)
int64


In [10]:
c = np.array([(12,21,82,10),
              (14,53,7,17)])
print(c)

[[12 21 82 10]
 [14 53  7 17]]


In [11]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
      [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)

(2, 2, 3)


Print 3 **rows** 3 **columns** of **ones**

In [12]:
x=np.ones((3,3), dtype=np.int16)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


TO PRINT 3 **TIMES** OF 3 **ROWS** 5 **COLUMNS** OF **ones**

In [16]:
y=np.ones((3,3,5), dtype=np.int16)
print(y)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


RESHAPE to 2 **ELEMENT** LISTS

In [19]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
print(e)

[[1 2 3]
 [4 5 6]]


In [21]:
print('First row:', e[0])
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [22]:
print('Second column:', e[:,1])

Second column: [2 5]


In [23]:
print(e[1, :2])

[4 5]


In [24]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

**HORIZONTAL AND VERTICAL STACK**

In [25]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))
print("Vertical append:")
print(np.vstack((f,g)))

Horizontal Append: [1 2 3 4 5 6]
Vertical append:
[[1 2 3]
 [4 5 6]]


TO FIND A **LIST** OF **RANDOM** **ELEMENTS**

In [27]:
normal_array = np.random.normal(15, 2, 5)
print(normal_array)

[16.62417335 13.85807366 18.28156571 16.09434572 13.43334681]


FIND **MIN** , **MAX**, **MEAN**, **MEDIAN**,**STD** FROM A LISTS

In [28]:
print(np.min(normal_array))
print(np.max(normal_array))
print(np.mean(normal_array))
print(np.median(normal_array))
print(np.std(normal_array))

13.433346806937667
18.281565708690927
15.65830104887356
16.09434571798151
1.7997667501631733


TO **PRINT** ELEMENTS IN **RANGE**

In [29]:
np.arange(1, 7)

array([1, 2, 3, 4, 5, 6])

In [30]:
np.arange(1, 11,3)

array([ 1,  4,  7, 10])

In [31]:
np.linspace(1.0, 11.0, num=10)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [32]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [33]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [34]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

TO FIND **DOT** PRODUCT OF **MATRIX**

In [36]:
f = np.array([12,21,34])
g = np.array([14,15,13])
np.dot(f, g)

925

TO FIND THE **INVERSE** OF MAT**R**IX

In [38]:
A = np.array([[16, 11, 12],
              [42, -21, 50],
              [21, 18, 17]])
print(np.linalg.inv(A))

[[ 0.6125731  -0.01413255 -0.39083821]
 [-0.16374269 -0.00974659  0.14424951]
 [-0.58333333  0.02777778  0.38888889]]


TO FIND THE **MATRIX** **MULTIPLICATION**

In [39]:
h = [[11,21],[13,14]] 
i = [[25,16],[27,18]] 
np.matmul(h, i)

array([[842, 554],
       [703, 460]])

TO FIND THE **DETERMINANT** OF MATRIX

In [41]:
n_array = np.array([[5, 9], [3, 4]])
print("Numpy Matrix is:")
print(n_array)
det = np.linalg.det(n_array)
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[5 9]
 [3 4]]

Determinant of given 2X2 matrix:
-7


TO FIND THE **RANK** OF **MATRIX**

In [42]:
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])
np.linalg.matrix_rank(mx)

3

TO FIND THE **TRANSPOSE** OF THE **MATRIX**

In [44]:
gfg = np.matrix('[14, 10; 1, 13]')
trans = gfg.transpose()
print(trans)

[[14  1]
 [10 13]]


TO FIND THE **TRACE** OF **MATRIX**

In [46]:
gfg = np.matrix('[14, 10; 1, 13]')
tracem = gfg.trace()
print(tracem)

[[27]]



TO FIND THE **EIGEN** **VALUES** AND **EIGEN** **VECTORS** OF MATRIX

In [48]:
example_matrix = np.array([
  [12,21,34,14],
  [15,16,17,18],
  [19,1,1,2],
  [3,4,5,6]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 47.30276129 -19.25720613   5.5298591    1.42458574] [[ 0.71948278  0.72607644  0.19211288  0.02292175]
 [ 0.60106675 -0.00383505 -0.79340268 -0.86426443]
 [ 0.31463257 -0.68577396  0.5389771   0.40316585]
 [ 0.14855855  0.05012354 -0.20762589  0.2999648 ]]
